export { parseMealText, extractParsedMeal } from './parse'
export { ParsedItemSchema, ParsedMealSchema } from './types'
export type { ParsedItem, ParsedMeal, ParseResult } from './types'
export { matchFood, normalizeFoodName } from './match'
export type { FoodMatch } from './match'
export { pickUnitKey, resolveGrams, computeItemMacros, buildMealItem } from './portion'
export type { GramsRange, ResolvedPortion, ItemMacros } from './portion'
