-- Migration 0007 — alias coverage fixes (bare-token gaps from the matchFood audit)
--
-- FOLDED INTO 0004 (#29): these alias updates now live directly in the 0004 seed
-- values, so a FRESH database needs only 0004 (its delete+re-insert no longer wipes
-- them). This file is intentionally a NO-OP, kept so Supabase's applied-migration
-- history (tracked by filename) stays intact — do NOT delete it.
--
-- For the record, 0007 previously made these changes (now in 0004):
--   • Boiled egg (whole): + 'egg','eggs','boiled eggs','ande','anda'
--   • Egg, whole (raw):   − 'anda' (so bare egg terms resolve to boiled, not raw)
--   • Cooked white rice:  + 'rice'
--   • Boiled kala chana:  + 'chana'
--   • Chapati / roti:     + 'chapati'

-- (no-op)
